kafka-to-rabbitmq: 
    - topic:   test
      from: 
        topic: test
      to:
        topic: d.t
        queue: test2
        exchange: test2
rabbitmq-to-kafka: 
    - topic:   test
      from:
        topic: d.t
        queue: test
        exchange: test
      to: 
        topic: test
    - topic:   test
      from:
        topic: d.t
        queue: test2
        exchange: test2
      to: 
        topic: test2


